void mergeZptHist(int nsel = 0) {
TString inputFolder = "/data/t3home000/ceballos/panda/v_005_0";

if(nsel == 0){ // NLO
const int nFiles = 6;
TFile *_file[nFiles];
_file[0] = TFile::Open(Form("%s/DYJetsToLL_Pt0To50.root"  , inputFolder.Data()));
_file[1] = TFile::Open(Form("%s/DYJetsToLL_Pt50To100.root", inputFolder.Data()));
_file[2] = TFile::Open(Form("%s/DYJetsToLL_Pt100To250.root",inputFolder.Data()));
_file[3] = TFile::Open(Form("%s/DYJetsToLL_Pt250To400.root",inputFolder.Data()));
_file[4] = TFile::Open(Form("%s/DYJetsToLL_Pt400To650.root",inputFolder.Data()));
_file[5] = TFile::Open(Form("%s/DYJetsToLL_Pt650ToInf.root",inputFolder.Data()));

double xs[6] = {5512.4400,374.6800,86.5200,3.3247,0.4491,0.0422};

TH1D *hDITotalMCWeight[nFiles];

TH1D *hDIDilPtMM[nFiles];     TH1D *hDIDilPtMM_PDF[nFiles];	TH1D *hDIDilPtMM_QCD[nFiles];	 
TH1D *hDIDilPtEE[nFiles];     TH1D *hDIDilPtEE_PDF[nFiles];	TH1D *hDIDilPtEE_QCD[nFiles];	 
TH1D *hDIDilRapMM[nFiles];    TH1D *hDIDilRapMM_PDF[nFiles];	TH1D *hDIDilRapMM_QCD[nFiles];   
TH1D *hDIDilRapEE[nFiles];    TH1D *hDIDilRapEE_PDF[nFiles];	TH1D *hDIDilRapEE_QCD[nFiles];   
TH1D *hDIDilPhiStarMM[nFiles];TH1D *hDIDilPhiStarMM_PDF[nFiles];TH1D *hDIDilPhiStarMM_QCD[nFiles];    
TH1D *hDIDilPhiStarEE[nFiles];TH1D *hDIDilPhiStarEE_PDF[nFiles];TH1D *hDIDilPhiStarEE_QCD[nFiles];    
TH1D *hDIDilPtRap0MM[nFiles]; TH1D *hDIDilPtRap0MM_PDF[nFiles]; TH1D *hDIDilPtRap0MM_QCD[nFiles];
TH1D *hDIDilPtRap0EE[nFiles]; TH1D *hDIDilPtRap0EE_PDF[nFiles]; TH1D *hDIDilPtRap0EE_QCD[nFiles];
TH1D *hDIDilPtRap1MM[nFiles]; TH1D *hDIDilPtRap1MM_PDF[nFiles]; TH1D *hDIDilPtRap1MM_QCD[nFiles];
TH1D *hDIDilPtRap1EE[nFiles]; TH1D *hDIDilPtRap1EE_PDF[nFiles]; TH1D *hDIDilPtRap1EE_QCD[nFiles];
TH1D *hDIDilPtRap2MM[nFiles]; TH1D *hDIDilPtRap2MM_PDF[nFiles]; TH1D *hDIDilPtRap2MM_QCD[nFiles];
TH1D *hDIDilPtRap2EE[nFiles]; TH1D *hDIDilPtRap2EE_PDF[nFiles]; TH1D *hDIDilPtRap2EE_QCD[nFiles];
TH1D *hDIDilPtRap3MM[nFiles]; TH1D *hDIDilPtRap3MM_PDF[nFiles]; TH1D *hDIDilPtRap3MM_QCD[nFiles];
TH1D *hDIDilPtRap3EE[nFiles]; TH1D *hDIDilPtRap3EE_PDF[nFiles]; TH1D *hDIDilPtRap3EE_QCD[nFiles];
TH1D *hDIDilPtRap4MM[nFiles]; TH1D *hDIDilPtRap4MM_PDF[nFiles]; TH1D *hDIDilPtRap4MM_QCD[nFiles];
TH1D *hDIDilPtRap4EE[nFiles]; TH1D *hDIDilPtRap4EE_PDF[nFiles]; TH1D *hDIDilPtRap4EE_QCD[nFiles];

for(int i=0; i<nFiles; i++){
  hDITotalMCWeight[i] = (TH1D*)_file[i]->Get("hDTotalMCWeight");	 

  hDIDilPtMM[i]       = (TH1D*)_file[i]->Get("hDDilPtMM");     hDIDilPtMM[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE[i]       = (TH1D*)_file[i]->Get("hDDilPtEE");     hDIDilPtEE[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM[i]      = (TH1D*)_file[i]->Get("hDDilRapMM");    hDIDilRapMM[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE[i]      = (TH1D*)_file[i]->Get("hDDilRapEE");    hDIDilRapEE[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM");hDIDilPhiStarMM[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE");hDIDilPhiStarEE[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM"); hDIDilPtRap0MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE"); hDIDilPtRap0EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM"); hDIDilPtRap1MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE"); hDIDilPtRap1EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM"); hDIDilPtRap2MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE"); hDIDilPtRap2EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM"); hDIDilPtRap3MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE"); hDIDilPtRap3EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM"); hDIDilPtRap4MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE"); hDIDilPtRap4EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());

  hDIDilPtMM_PDF[i]       = (TH1D*)_file[i]->Get("hDDilPtMM_PDF");     hDIDilPtMM_PDF[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE_PDF[i]       = (TH1D*)_file[i]->Get("hDDilPtEE_PDF");     hDIDilPtEE_PDF[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM_PDF[i]      = (TH1D*)_file[i]->Get("hDDilRapMM_PDF");    hDIDilRapMM_PDF[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE_PDF[i]      = (TH1D*)_file[i]->Get("hDDilRapEE_PDF");    hDIDilRapEE_PDF[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM_PDF[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM_PDF");hDIDilPhiStarMM_PDF[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE_PDF[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE_PDF");hDIDilPhiStarEE_PDF[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM_PDF"); hDIDilPtRap0MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE_PDF"); hDIDilPtRap0EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM_PDF"); hDIDilPtRap1MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE_PDF"); hDIDilPtRap1EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM_PDF"); hDIDilPtRap2MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE_PDF"); hDIDilPtRap2EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM_PDF"); hDIDilPtRap3MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE_PDF"); hDIDilPtRap3EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM_PDF"); hDIDilPtRap4MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE_PDF"); hDIDilPtRap4EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());

  hDIDilPtMM_QCD[i]       = (TH1D*)_file[i]->Get("hDDilPtMM_QCD");     hDIDilPtMM_QCD[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE_QCD[i]       = (TH1D*)_file[i]->Get("hDDilPtEE_QCD");     hDIDilPtEE_QCD[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM_QCD[i]      = (TH1D*)_file[i]->Get("hDDilRapMM_QCD");    hDIDilRapMM_QCD[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE_QCD[i]      = (TH1D*)_file[i]->Get("hDDilRapEE_QCD");    hDIDilRapEE_QCD[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM_QCD[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM_QCD");hDIDilPhiStarMM_QCD[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE_QCD[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE_QCD");hDIDilPhiStarEE_QCD[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM_QCD"); hDIDilPtRap0MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE_QCD"); hDIDilPtRap0EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM_QCD"); hDIDilPtRap1MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE_QCD"); hDIDilPtRap1EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM_QCD"); hDIDilPtRap2MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE_QCD"); hDIDilPtRap2EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM_QCD"); hDIDilPtRap3MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE_QCD"); hDIDilPtRap3EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM_QCD"); hDIDilPtRap4MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE_QCD"); hDIDilPtRap4EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
}

TH1D *hDDilPtMM      = (TH1D*)hDIDilPtMM     [0]->Clone();
TH1D *hDDilPtEE      = (TH1D*)hDIDilPtEE     [0]->Clone();
TH1D *hDDilRapMM     = (TH1D*)hDIDilRapMM    [0]->Clone();
TH1D *hDDilRapEE     = (TH1D*)hDIDilRapEE    [0]->Clone();
TH1D *hDDilPhiStarMM = (TH1D*)hDIDilPhiStarMM[0]->Clone();
TH1D *hDDilPhiStarEE = (TH1D*)hDIDilPhiStarEE[0]->Clone();
TH1D *hDDilPtRap0MM  = (TH1D*)hDIDilPtRap0MM [0]->Clone();
TH1D *hDDilPtRap0EE  = (TH1D*)hDIDilPtRap0EE [0]->Clone();
TH1D *hDDilPtRap1MM  = (TH1D*)hDIDilPtRap1MM [0]->Clone();
TH1D *hDDilPtRap1EE  = (TH1D*)hDIDilPtRap1EE [0]->Clone();
TH1D *hDDilPtRap2MM  = (TH1D*)hDIDilPtRap2MM [0]->Clone();
TH1D *hDDilPtRap2EE  = (TH1D*)hDIDilPtRap2EE [0]->Clone();
TH1D *hDDilPtRap3MM  = (TH1D*)hDIDilPtRap3MM [0]->Clone();
TH1D *hDDilPtRap3EE  = (TH1D*)hDIDilPtRap3EE [0]->Clone();
TH1D *hDDilPtRap4MM  = (TH1D*)hDIDilPtRap4MM [0]->Clone();
TH1D *hDDilPtRap4EE  = (TH1D*)hDIDilPtRap4EE [0]->Clone();

TH1D *hDDilPtMM_PDF      = (TH1D*)hDIDilPtMM_PDF     [0]->Clone();
TH1D *hDDilPtEE_PDF      = (TH1D*)hDIDilPtEE_PDF     [0]->Clone();
TH1D *hDDilRapMM_PDF     = (TH1D*)hDIDilRapMM_PDF    [0]->Clone();
TH1D *hDDilRapEE_PDF     = (TH1D*)hDIDilRapEE_PDF    [0]->Clone();
TH1D *hDDilPhiStarMM_PDF = (TH1D*)hDIDilPhiStarMM_PDF[0]->Clone();
TH1D *hDDilPhiStarEE_PDF = (TH1D*)hDIDilPhiStarEE_PDF[0]->Clone();
TH1D *hDDilPtRap0MM_PDF  = (TH1D*)hDIDilPtRap0MM_PDF [0]->Clone();
TH1D *hDDilPtRap0EE_PDF  = (TH1D*)hDIDilPtRap0EE_PDF [0]->Clone();
TH1D *hDDilPtRap1MM_PDF  = (TH1D*)hDIDilPtRap1MM_PDF [0]->Clone();
TH1D *hDDilPtRap1EE_PDF  = (TH1D*)hDIDilPtRap1EE_PDF [0]->Clone();
TH1D *hDDilPtRap2MM_PDF  = (TH1D*)hDIDilPtRap2MM_PDF [0]->Clone();
TH1D *hDDilPtRap2EE_PDF  = (TH1D*)hDIDilPtRap2EE_PDF [0]->Clone();
TH1D *hDDilPtRap3MM_PDF  = (TH1D*)hDIDilPtRap3MM_PDF [0]->Clone();
TH1D *hDDilPtRap3EE_PDF  = (TH1D*)hDIDilPtRap3EE_PDF [0]->Clone();
TH1D *hDDilPtRap4MM_PDF  = (TH1D*)hDIDilPtRap4MM_PDF [0]->Clone();
TH1D *hDDilPtRap4EE_PDF  = (TH1D*)hDIDilPtRap4EE_PDF [0]->Clone();

TH1D *hDDilPtMM_QCD      = (TH1D*)hDIDilPtMM_QCD     [0]->Clone();
TH1D *hDDilPtEE_QCD      = (TH1D*)hDIDilPtEE_QCD     [0]->Clone();
TH1D *hDDilRapMM_QCD     = (TH1D*)hDIDilRapMM_QCD    [0]->Clone();
TH1D *hDDilRapEE_QCD     = (TH1D*)hDIDilRapEE_QCD    [0]->Clone();
TH1D *hDDilPhiStarMM_QCD = (TH1D*)hDIDilPhiStarMM_QCD[0]->Clone();
TH1D *hDDilPhiStarEE_QCD = (TH1D*)hDIDilPhiStarEE_QCD[0]->Clone();
TH1D *hDDilPtRap0MM_QCD  = (TH1D*)hDIDilPtRap0MM_QCD [0]->Clone();
TH1D *hDDilPtRap0EE_QCD  = (TH1D*)hDIDilPtRap0EE_QCD [0]->Clone();
TH1D *hDDilPtRap1MM_QCD  = (TH1D*)hDIDilPtRap1MM_QCD [0]->Clone();
TH1D *hDDilPtRap1EE_QCD  = (TH1D*)hDIDilPtRap1EE_QCD [0]->Clone();
TH1D *hDDilPtRap2MM_QCD  = (TH1D*)hDIDilPtRap2MM_QCD [0]->Clone();
TH1D *hDDilPtRap2EE_QCD  = (TH1D*)hDIDilPtRap2EE_QCD [0]->Clone();
TH1D *hDDilPtRap3MM_QCD  = (TH1D*)hDIDilPtRap3MM_QCD [0]->Clone();
TH1D *hDDilPtRap3EE_QCD  = (TH1D*)hDIDilPtRap3EE_QCD [0]->Clone();
TH1D *hDDilPtRap4MM_QCD  = (TH1D*)hDIDilPtRap4MM_QCD [0]->Clone();
TH1D *hDDilPtRap4EE_QCD  = (TH1D*)hDIDilPtRap4EE_QCD [0]->Clone();

for(int i=1; i<nFiles; i++){
  hDDilPtMM	->Add(hDIDilPtMM     [i]);   
  hDDilPtEE	->Add(hDIDilPtEE     [i]);   
  hDDilRapMM	->Add(hDIDilRapMM    [i]);  
  hDDilRapEE	->Add(hDIDilRapEE    [i]);  
  hDDilPhiStarMM->Add(hDIDilPhiStarMM[i]);  
  hDDilPhiStarEE->Add(hDIDilPhiStarEE[i]);  
  hDDilPtRap0MM ->Add(hDIDilPtRap0MM [i]);  
  hDDilPtRap0EE ->Add(hDIDilPtRap0EE [i]);  
  hDDilPtRap1MM ->Add(hDIDilPtRap1MM [i]);
  hDDilPtRap1EE ->Add(hDIDilPtRap1EE [i]);
  hDDilPtRap2MM ->Add(hDIDilPtRap2MM [i]);
  hDDilPtRap2EE ->Add(hDIDilPtRap2EE [i]);
  hDDilPtRap3MM ->Add(hDIDilPtRap3MM [i]);
  hDDilPtRap3EE ->Add(hDIDilPtRap3EE [i]);
  hDDilPtRap4MM ->Add(hDIDilPtRap4MM [i]);
  hDDilPtRap4EE ->Add(hDIDilPtRap4EE [i]);

  hDDilPtMM_PDF     ->Add(hDIDilPtMM_PDF     [i]);   
  hDDilPtEE_PDF     ->Add(hDIDilPtEE_PDF     [i]);   
  hDDilRapMM_PDF    ->Add(hDIDilRapMM_PDF    [i]);  
  hDDilRapEE_PDF    ->Add(hDIDilRapEE_PDF    [i]);  
  hDDilPhiStarMM_PDF->Add(hDIDilPhiStarMM_PDF[i]);  
  hDDilPhiStarEE_PDF->Add(hDIDilPhiStarEE_PDF[i]);  
  hDDilPtRap0MM_PDF ->Add(hDIDilPtRap0MM_PDF [i]);  
  hDDilPtRap0EE_PDF ->Add(hDIDilPtRap0EE_PDF [i]);  
  hDDilPtRap1MM_PDF ->Add(hDIDilPtRap1MM_PDF [i]);
  hDDilPtRap1EE_PDF ->Add(hDIDilPtRap1EE_PDF [i]);
  hDDilPtRap2MM_PDF ->Add(hDIDilPtRap2MM_PDF [i]);
  hDDilPtRap2EE_PDF ->Add(hDIDilPtRap2EE_PDF [i]);
  hDDilPtRap3MM_PDF ->Add(hDIDilPtRap3MM_PDF [i]);
  hDDilPtRap3EE_PDF ->Add(hDIDilPtRap3EE_PDF [i]);
  hDDilPtRap4MM_PDF ->Add(hDIDilPtRap4MM_PDF [i]);
  hDDilPtRap4EE_PDF ->Add(hDIDilPtRap4EE_PDF [i]);

  hDDilPtMM_QCD     ->Add(hDIDilPtMM_QCD     [i]);   
  hDDilPtEE_QCD     ->Add(hDIDilPtEE_QCD     [i]);   
  hDDilRapMM_QCD    ->Add(hDIDilRapMM_QCD    [i]);  
  hDDilRapEE_QCD    ->Add(hDIDilRapEE_QCD    [i]);  
  hDDilPhiStarMM_QCD->Add(hDIDilPhiStarMM_QCD[i]);  
  hDDilPhiStarEE_QCD->Add(hDIDilPhiStarEE_QCD[i]);  
  hDDilPtRap0MM_QCD ->Add(hDIDilPtRap0MM_QCD [i]);  
  hDDilPtRap0EE_QCD ->Add(hDIDilPtRap0EE_QCD [i]);  
  hDDilPtRap1MM_QCD ->Add(hDIDilPtRap1MM_QCD [i]);
  hDDilPtRap1EE_QCD ->Add(hDIDilPtRap1EE_QCD [i]);
  hDDilPtRap2MM_QCD ->Add(hDIDilPtRap2MM_QCD [i]);
  hDDilPtRap2EE_QCD ->Add(hDIDilPtRap2EE_QCD [i]);
  hDDilPtRap3MM_QCD ->Add(hDIDilPtRap3MM_QCD [i]);
  hDDilPtRap3EE_QCD ->Add(hDIDilPtRap3EE_QCD [i]);
  hDDilPtRap4MM_QCD ->Add(hDIDilPtRap4MM_QCD [i]);
  hDDilPtRap4EE_QCD ->Add(hDIDilPtRap4EE_QCD [i]);
}

TFile myOutputFile("genZpt_NLO.root","RECREATE");
  hDDilPtMM	->Write(); 
  hDDilPtEE	->Write(); 
  hDDilRapMM	->Write();
  hDDilRapEE	->Write();
  hDDilPhiStarMM->Write();
  hDDilPhiStarEE->Write();
  hDDilPtRap0MM ->Write();
  hDDilPtRap0EE ->Write();
  hDDilPtRap1MM ->Write();
  hDDilPtRap1EE ->Write();
  hDDilPtRap2MM ->Write();
  hDDilPtRap2EE ->Write();
  hDDilPtRap3MM ->Write();
  hDDilPtRap3EE ->Write();
  hDDilPtRap4MM ->Write();
  hDDilPtRap4EE ->Write();

  hDDilPtMM_PDF     ->Write(); 
  hDDilPtEE_PDF     ->Write(); 
  hDDilRapMM_PDF    ->Write();
  hDDilRapEE_PDF    ->Write();
  hDDilPhiStarMM_PDF->Write();
  hDDilPhiStarEE_PDF->Write();
  hDDilPtRap0MM_PDF ->Write();
  hDDilPtRap0EE_PDF ->Write();
  hDDilPtRap1MM_PDF ->Write();
  hDDilPtRap1EE_PDF ->Write();
  hDDilPtRap2MM_PDF ->Write();
  hDDilPtRap2EE_PDF ->Write();
  hDDilPtRap3MM_PDF ->Write();
  hDDilPtRap3EE_PDF ->Write();
  hDDilPtRap4MM_PDF ->Write();
  hDDilPtRap4EE_PDF ->Write();

  hDDilPtMM_QCD     ->Write(); 
  hDDilPtEE_QCD     ->Write(); 
  hDDilRapMM_QCD    ->Write();
  hDDilRapEE_QCD    ->Write();
  hDDilPhiStarMM_QCD->Write();
  hDDilPhiStarEE_QCD->Write();
  hDDilPtRap0MM_QCD ->Write();
  hDDilPtRap0EE_QCD ->Write();
  hDDilPtRap1MM_QCD ->Write();
  hDDilPtRap1EE_QCD ->Write();
  hDDilPtRap2MM_QCD ->Write();
  hDDilPtRap2EE_QCD ->Write();
  hDDilPtRap3MM_QCD ->Write();
  hDDilPtRap3EE_QCD ->Write();
  hDDilPtRap4MM_QCD ->Write();
  hDDilPtRap4EE_QCD ->Write();
myOutputFile.Close();

} else { // LO
const int nFiles = 3;
TFile *_file[nFiles];
_file[0] = TFile::Open(Form("%s/DYJetsToLL_M-50_LO_Pt000To050.root", inputFolder.Data()));
_file[1] = TFile::Open(Form("%s/DYJetsToLL_M-50_LO_Pt100to200.root", inputFolder.Data()));
_file[2] = TFile::Open(Form("%s/DYJetsToLL_M-50_LO_Pt200toInf.root",inputFolder.Data()));

double xs[nFiles] = {2008.4*3,69.586,8.186};

TH1D *hDITotalMCWeight[nFiles];

TH1D *hDIDilPtMM[nFiles];     TH1D *hDIDilPtMM_PDF[nFiles];	TH1D *hDIDilPtMM_QCD[nFiles];	 
TH1D *hDIDilPtEE[nFiles];     TH1D *hDIDilPtEE_PDF[nFiles];	TH1D *hDIDilPtEE_QCD[nFiles];	 
TH1D *hDIDilRapMM[nFiles];    TH1D *hDIDilRapMM_PDF[nFiles];	TH1D *hDIDilRapMM_QCD[nFiles];   
TH1D *hDIDilRapEE[nFiles];    TH1D *hDIDilRapEE_PDF[nFiles];	TH1D *hDIDilRapEE_QCD[nFiles];   
TH1D *hDIDilPhiStarMM[nFiles];TH1D *hDIDilPhiStarMM_PDF[nFiles];TH1D *hDIDilPhiStarMM_QCD[nFiles];    
TH1D *hDIDilPhiStarEE[nFiles];TH1D *hDIDilPhiStarEE_PDF[nFiles];TH1D *hDIDilPhiStarEE_QCD[nFiles];    
TH1D *hDIDilPtRap0MM[nFiles]; TH1D *hDIDilPtRap0MM_PDF[nFiles]; TH1D *hDIDilPtRap0MM_QCD[nFiles];
TH1D *hDIDilPtRap0EE[nFiles]; TH1D *hDIDilPtRap0EE_PDF[nFiles]; TH1D *hDIDilPtRap0EE_QCD[nFiles];
TH1D *hDIDilPtRap1MM[nFiles]; TH1D *hDIDilPtRap1MM_PDF[nFiles]; TH1D *hDIDilPtRap1MM_QCD[nFiles];
TH1D *hDIDilPtRap1EE[nFiles]; TH1D *hDIDilPtRap1EE_PDF[nFiles]; TH1D *hDIDilPtRap1EE_QCD[nFiles];
TH1D *hDIDilPtRap2MM[nFiles]; TH1D *hDIDilPtRap2MM_PDF[nFiles]; TH1D *hDIDilPtRap2MM_QCD[nFiles];
TH1D *hDIDilPtRap2EE[nFiles]; TH1D *hDIDilPtRap2EE_PDF[nFiles]; TH1D *hDIDilPtRap2EE_QCD[nFiles];
TH1D *hDIDilPtRap3MM[nFiles]; TH1D *hDIDilPtRap3MM_PDF[nFiles]; TH1D *hDIDilPtRap3MM_QCD[nFiles];
TH1D *hDIDilPtRap3EE[nFiles]; TH1D *hDIDilPtRap3EE_PDF[nFiles]; TH1D *hDIDilPtRap3EE_QCD[nFiles];
TH1D *hDIDilPtRap4MM[nFiles]; TH1D *hDIDilPtRap4MM_PDF[nFiles]; TH1D *hDIDilPtRap4MM_QCD[nFiles];
TH1D *hDIDilPtRap4EE[nFiles]; TH1D *hDIDilPtRap4EE_PDF[nFiles]; TH1D *hDIDilPtRap4EE_QCD[nFiles];

for(int i=0; i<nFiles; i++){
  hDITotalMCWeight[i] = (TH1D*)_file[i]->Get("hDTotalMCWeight");	 

  hDIDilPtMM[i]       = (TH1D*)_file[i]->Get("hDDilPtMM");     hDIDilPtMM[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE[i]       = (TH1D*)_file[i]->Get("hDDilPtEE");     hDIDilPtEE[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM[i]      = (TH1D*)_file[i]->Get("hDDilRapMM");    hDIDilRapMM[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE[i]      = (TH1D*)_file[i]->Get("hDDilRapEE");    hDIDilRapEE[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM");hDIDilPhiStarMM[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE");hDIDilPhiStarEE[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM"); hDIDilPtRap0MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE"); hDIDilPtRap0EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM"); hDIDilPtRap1MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE"); hDIDilPtRap1EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM"); hDIDilPtRap2MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE"); hDIDilPtRap2EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM"); hDIDilPtRap3MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE"); hDIDilPtRap3EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM"); hDIDilPtRap4MM[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE"); hDIDilPtRap4EE[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());

  hDIDilPtMM_PDF[i]       = (TH1D*)_file[i]->Get("hDDilPtMM_PDF");     hDIDilPtMM_PDF[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE_PDF[i]       = (TH1D*)_file[i]->Get("hDDilPtEE_PDF");     hDIDilPtEE_PDF[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM_PDF[i]      = (TH1D*)_file[i]->Get("hDDilRapMM_PDF");    hDIDilRapMM_PDF[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE_PDF[i]      = (TH1D*)_file[i]->Get("hDDilRapEE_PDF");    hDIDilRapEE_PDF[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM_PDF[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM_PDF");hDIDilPhiStarMM_PDF[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE_PDF[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE_PDF");hDIDilPhiStarEE_PDF[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM_PDF"); hDIDilPtRap0MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE_PDF"); hDIDilPtRap0EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM_PDF"); hDIDilPtRap1MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE_PDF"); hDIDilPtRap1EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM_PDF"); hDIDilPtRap2MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE_PDF"); hDIDilPtRap2EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM_PDF"); hDIDilPtRap3MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE_PDF"); hDIDilPtRap3EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM_PDF"); hDIDilPtRap4MM_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE_PDF[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE_PDF"); hDIDilPtRap4EE_PDF[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());

  hDIDilPtMM_QCD[i]       = (TH1D*)_file[i]->Get("hDDilPtMM_QCD");     hDIDilPtMM_QCD[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilPtEE_QCD[i]       = (TH1D*)_file[i]->Get("hDDilPtEE_QCD");     hDIDilPtEE_QCD[i]     ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());  
  hDIDilRapMM_QCD[i]      = (TH1D*)_file[i]->Get("hDDilRapMM_QCD");    hDIDilRapMM_QCD[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilRapEE_QCD[i]      = (TH1D*)_file[i]->Get("hDDilRapEE_QCD");    hDIDilRapEE_QCD[i]    ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights()); 
  hDIDilPhiStarMM_QCD[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarMM_QCD");hDIDilPhiStarMM_QCD[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPhiStarEE_QCD[i]  = (TH1D*)_file[i]->Get("hDDilPhiStarEE_QCD");hDIDilPhiStarEE_QCD[i]->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());       
  hDIDilPtRap0MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0MM_QCD"); hDIDilPtRap0MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap0EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap0EE_QCD"); hDIDilPtRap0EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1MM_QCD"); hDIDilPtRap1MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap1EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap1EE_QCD"); hDIDilPtRap1EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2MM_QCD"); hDIDilPtRap2MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap2EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap2EE_QCD"); hDIDilPtRap2EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3MM_QCD"); hDIDilPtRap3MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap3EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap3EE_QCD"); hDIDilPtRap3EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4MM_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4MM_QCD"); hDIDilPtRap4MM_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
  hDIDilPtRap4EE_QCD[i]   = (TH1D*)_file[i]->Get("hDDilPtRap4EE_QCD"); hDIDilPtRap4EE_QCD[i] ->Scale(xs[i]/hDITotalMCWeight[i]->GetSumOfWeights());
}

TH1D *hDDilPtMM      = (TH1D*)hDIDilPtMM     [0]->Clone();
TH1D *hDDilPtEE      = (TH1D*)hDIDilPtEE     [0]->Clone();
TH1D *hDDilRapMM     = (TH1D*)hDIDilRapMM    [0]->Clone();
TH1D *hDDilRapEE     = (TH1D*)hDIDilRapEE    [0]->Clone();
TH1D *hDDilPhiStarMM = (TH1D*)hDIDilPhiStarMM[0]->Clone();
TH1D *hDDilPhiStarEE = (TH1D*)hDIDilPhiStarEE[0]->Clone();
TH1D *hDDilPtRap0MM  = (TH1D*)hDIDilPtRap0MM [0]->Clone();
TH1D *hDDilPtRap0EE  = (TH1D*)hDIDilPtRap0EE [0]->Clone();
TH1D *hDDilPtRap1MM  = (TH1D*)hDIDilPtRap1MM [0]->Clone();
TH1D *hDDilPtRap1EE  = (TH1D*)hDIDilPtRap1EE [0]->Clone();
TH1D *hDDilPtRap2MM  = (TH1D*)hDIDilPtRap2MM [0]->Clone();
TH1D *hDDilPtRap2EE  = (TH1D*)hDIDilPtRap2EE [0]->Clone();
TH1D *hDDilPtRap3MM  = (TH1D*)hDIDilPtRap3MM [0]->Clone();
TH1D *hDDilPtRap3EE  = (TH1D*)hDIDilPtRap3EE [0]->Clone();
TH1D *hDDilPtRap4MM  = (TH1D*)hDIDilPtRap4MM [0]->Clone();
TH1D *hDDilPtRap4EE  = (TH1D*)hDIDilPtRap4EE [0]->Clone();

TH1D *hDDilPtMM_PDF      = (TH1D*)hDIDilPtMM_PDF     [0]->Clone();
TH1D *hDDilPtEE_PDF      = (TH1D*)hDIDilPtEE_PDF     [0]->Clone();
TH1D *hDDilRapMM_PDF     = (TH1D*)hDIDilRapMM_PDF    [0]->Clone();
TH1D *hDDilRapEE_PDF     = (TH1D*)hDIDilRapEE_PDF    [0]->Clone();
TH1D *hDDilPhiStarMM_PDF = (TH1D*)hDIDilPhiStarMM_PDF[0]->Clone();
TH1D *hDDilPhiStarEE_PDF = (TH1D*)hDIDilPhiStarEE_PDF[0]->Clone();
TH1D *hDDilPtRap0MM_PDF  = (TH1D*)hDIDilPtRap0MM_PDF [0]->Clone();
TH1D *hDDilPtRap0EE_PDF  = (TH1D*)hDIDilPtRap0EE_PDF [0]->Clone();
TH1D *hDDilPtRap1MM_PDF  = (TH1D*)hDIDilPtRap1MM_PDF [0]->Clone();
TH1D *hDDilPtRap1EE_PDF  = (TH1D*)hDIDilPtRap1EE_PDF [0]->Clone();
TH1D *hDDilPtRap2MM_PDF  = (TH1D*)hDIDilPtRap2MM_PDF [0]->Clone();
TH1D *hDDilPtRap2EE_PDF  = (TH1D*)hDIDilPtRap2EE_PDF [0]->Clone();
TH1D *hDDilPtRap3MM_PDF  = (TH1D*)hDIDilPtRap3MM_PDF [0]->Clone();
TH1D *hDDilPtRap3EE_PDF  = (TH1D*)hDIDilPtRap3EE_PDF [0]->Clone();
TH1D *hDDilPtRap4MM_PDF  = (TH1D*)hDIDilPtRap4MM_PDF [0]->Clone();
TH1D *hDDilPtRap4EE_PDF  = (TH1D*)hDIDilPtRap4EE_PDF [0]->Clone();

TH1D *hDDilPtMM_QCD      = (TH1D*)hDIDilPtMM_QCD     [0]->Clone();
TH1D *hDDilPtEE_QCD      = (TH1D*)hDIDilPtEE_QCD     [0]->Clone();
TH1D *hDDilRapMM_QCD     = (TH1D*)hDIDilRapMM_QCD    [0]->Clone();
TH1D *hDDilRapEE_QCD     = (TH1D*)hDIDilRapEE_QCD    [0]->Clone();
TH1D *hDDilPhiStarMM_QCD = (TH1D*)hDIDilPhiStarMM_QCD[0]->Clone();
TH1D *hDDilPhiStarEE_QCD = (TH1D*)hDIDilPhiStarEE_QCD[0]->Clone();
TH1D *hDDilPtRap0MM_QCD  = (TH1D*)hDIDilPtRap0MM_QCD [0]->Clone();
TH1D *hDDilPtRap0EE_QCD  = (TH1D*)hDIDilPtRap0EE_QCD [0]->Clone();
TH1D *hDDilPtRap1MM_QCD  = (TH1D*)hDIDilPtRap1MM_QCD [0]->Clone();
TH1D *hDDilPtRap1EE_QCD  = (TH1D*)hDIDilPtRap1EE_QCD [0]->Clone();
TH1D *hDDilPtRap2MM_QCD  = (TH1D*)hDIDilPtRap2MM_QCD [0]->Clone();
TH1D *hDDilPtRap2EE_QCD  = (TH1D*)hDIDilPtRap2EE_QCD [0]->Clone();
TH1D *hDDilPtRap3MM_QCD  = (TH1D*)hDIDilPtRap3MM_QCD [0]->Clone();
TH1D *hDDilPtRap3EE_QCD  = (TH1D*)hDIDilPtRap3EE_QCD [0]->Clone();
TH1D *hDDilPtRap4MM_QCD  = (TH1D*)hDIDilPtRap4MM_QCD [0]->Clone();
TH1D *hDDilPtRap4EE_QCD  = (TH1D*)hDIDilPtRap4EE_QCD [0]->Clone();

for(int i=1; i<nFiles; i++){
  hDDilPtMM	->Add(hDIDilPtMM     [i]);   
  hDDilPtEE	->Add(hDIDilPtEE     [i]);   
  hDDilRapMM	->Add(hDIDilRapMM    [i]);  
  hDDilRapEE	->Add(hDIDilRapEE    [i]);  
  hDDilPhiStarMM->Add(hDIDilPhiStarMM[i]);  
  hDDilPhiStarEE->Add(hDIDilPhiStarEE[i]);  
  hDDilPtRap0MM ->Add(hDIDilPtRap0MM [i]);  
  hDDilPtRap0EE ->Add(hDIDilPtRap0EE [i]);  
  hDDilPtRap1MM ->Add(hDIDilPtRap1MM [i]);
  hDDilPtRap1EE ->Add(hDIDilPtRap1EE [i]);
  hDDilPtRap2MM ->Add(hDIDilPtRap2MM [i]);
  hDDilPtRap2EE ->Add(hDIDilPtRap2EE [i]);
  hDDilPtRap3MM ->Add(hDIDilPtRap3MM [i]);
  hDDilPtRap3EE ->Add(hDIDilPtRap3EE [i]);
  hDDilPtRap4MM ->Add(hDIDilPtRap4MM [i]);
  hDDilPtRap4EE ->Add(hDIDilPtRap4EE [i]);

  hDDilPtMM_PDF     ->Add(hDIDilPtMM_PDF     [i]);   
  hDDilPtEE_PDF     ->Add(hDIDilPtEE_PDF     [i]);   
  hDDilRapMM_PDF    ->Add(hDIDilRapMM_PDF    [i]);  
  hDDilRapEE_PDF    ->Add(hDIDilRapEE_PDF    [i]);  
  hDDilPhiStarMM_PDF->Add(hDIDilPhiStarMM_PDF[i]);  
  hDDilPhiStarEE_PDF->Add(hDIDilPhiStarEE_PDF[i]);  
  hDDilPtRap0MM_PDF ->Add(hDIDilPtRap0MM_PDF [i]);  
  hDDilPtRap0EE_PDF ->Add(hDIDilPtRap0EE_PDF [i]);  
  hDDilPtRap1MM_PDF ->Add(hDIDilPtRap1MM_PDF [i]);
  hDDilPtRap1EE_PDF ->Add(hDIDilPtRap1EE_PDF [i]);
  hDDilPtRap2MM_PDF ->Add(hDIDilPtRap2MM_PDF [i]);
  hDDilPtRap2EE_PDF ->Add(hDIDilPtRap2EE_PDF [i]);
  hDDilPtRap3MM_PDF ->Add(hDIDilPtRap3MM_PDF [i]);
  hDDilPtRap3EE_PDF ->Add(hDIDilPtRap3EE_PDF [i]);
  hDDilPtRap4MM_PDF ->Add(hDIDilPtRap4MM_PDF [i]);
  hDDilPtRap4EE_PDF ->Add(hDIDilPtRap4EE_PDF [i]);

  hDDilPtMM_QCD     ->Add(hDIDilPtMM_QCD     [i]);   
  hDDilPtEE_QCD     ->Add(hDIDilPtEE_QCD     [i]);   
  hDDilRapMM_QCD    ->Add(hDIDilRapMM_QCD    [i]);  
  hDDilRapEE_QCD    ->Add(hDIDilRapEE_QCD    [i]);  
  hDDilPhiStarMM_QCD->Add(hDIDilPhiStarMM_QCD[i]);  
  hDDilPhiStarEE_QCD->Add(hDIDilPhiStarEE_QCD[i]);  
  hDDilPtRap0MM_QCD ->Add(hDIDilPtRap0MM_QCD [i]);  
  hDDilPtRap0EE_QCD ->Add(hDIDilPtRap0EE_QCD [i]);  
  hDDilPtRap1MM_QCD ->Add(hDIDilPtRap1MM_QCD [i]);
  hDDilPtRap1EE_QCD ->Add(hDIDilPtRap1EE_QCD [i]);
  hDDilPtRap2MM_QCD ->Add(hDIDilPtRap2MM_QCD [i]);
  hDDilPtRap2EE_QCD ->Add(hDIDilPtRap2EE_QCD [i]);
  hDDilPtRap3MM_QCD ->Add(hDIDilPtRap3MM_QCD [i]);
  hDDilPtRap3EE_QCD ->Add(hDIDilPtRap3EE_QCD [i]);
  hDDilPtRap4MM_QCD ->Add(hDIDilPtRap4MM_QCD [i]);
  hDDilPtRap4EE_QCD ->Add(hDIDilPtRap4EE_QCD [i]);
}

TFile myOutputFile("genZpt_LO.root","RECREATE");
  hDDilPtMM	->Write(); 
  hDDilPtEE	->Write(); 
  hDDilRapMM	->Write();
  hDDilRapEE	->Write();
  hDDilPhiStarMM->Write();
  hDDilPhiStarEE->Write();
  hDDilPtRap0MM ->Write();
  hDDilPtRap0EE ->Write();
  hDDilPtRap1MM ->Write();
  hDDilPtRap1EE ->Write();
  hDDilPtRap2MM ->Write();
  hDDilPtRap2EE ->Write();
  hDDilPtRap3MM ->Write();
  hDDilPtRap3EE ->Write();
  hDDilPtRap4MM ->Write();
  hDDilPtRap4EE ->Write();

  hDDilPtMM_PDF     ->Write(); 
  hDDilPtEE_PDF     ->Write(); 
  hDDilRapMM_PDF    ->Write();
  hDDilRapEE_PDF    ->Write();
  hDDilPhiStarMM_PDF->Write();
  hDDilPhiStarEE_PDF->Write();
  hDDilPtRap0MM_PDF ->Write();
  hDDilPtRap0EE_PDF ->Write();
  hDDilPtRap1MM_PDF ->Write();
  hDDilPtRap1EE_PDF ->Write();
  hDDilPtRap2MM_PDF ->Write();
  hDDilPtRap2EE_PDF ->Write();
  hDDilPtRap3MM_PDF ->Write();
  hDDilPtRap3EE_PDF ->Write();
  hDDilPtRap4MM_PDF ->Write();
  hDDilPtRap4EE_PDF ->Write();

  hDDilPtMM_QCD     ->Write(); 
  hDDilPtEE_QCD     ->Write(); 
  hDDilRapMM_QCD    ->Write();
  hDDilRapEE_QCD    ->Write();
  hDDilPhiStarMM_QCD->Write();
  hDDilPhiStarEE_QCD->Write();
  hDDilPtRap0MM_QCD ->Write();
  hDDilPtRap0EE_QCD ->Write();
  hDDilPtRap1MM_QCD ->Write();
  hDDilPtRap1EE_QCD ->Write();
  hDDilPtRap2MM_QCD ->Write();
  hDDilPtRap2EE_QCD ->Write();
  hDDilPtRap3MM_QCD ->Write();
  hDDilPtRap3EE_QCD ->Write();
  hDDilPtRap4MM_QCD ->Write();
  hDDilPtRap4EE_QCD ->Write();
myOutputFile.Close();
}
}
